name: 'File Changes'
description: 'A customisable filter that uses git (or a custom command) to get changed files based on rules and sets them to outputs'
author: 'Jethro Muller'
branding:
  color: blue
  icon: file-text

inputs:
  base-branch:
    required: false
    description: 'The name of the branch being compared to. Uses $GITHUB_BASE_REF if not set'
    default: ${{ github.base_ref }}
  command:
    required: false
    description: 'The command to run to get the file changes can contain {globs} and {branchName} to specify replacements. {globs} uses glob-template to prepare the globs before replacement.'
    default: 'git diff --name-status --no-renames {branchName} -- {globs}'
  glob-template:
    required: false
    description: 'How to format the globs received'
    default: "'{glob}'"
  filter-patterns:
    required: false
    description: |
      A map with keys ADDED, CHANGED, and DELETED as keys and a pattern as a value. The matching is done by checking if the file change starts with the pattern.
    default: |
      ADDED: "A\t"
      CHANGED: "M\t"
      DELETED: "D\t"
  change-map:
    required: true
    description: |
      A multi-line map of changes to find. Each input in the change-map has two (or three with separateDeleted set to true) corresponding outputs.
      For a given key in change-map `code` there will be outputs `code`, a list of all the changed files, `any-code`, a boolean indicating if there were any changes that matched the glob filters, and `deleted-code` if `separateDeleted` is true.

      Example:
      python_files: {"globs": "*.py", "separateDeleted": false}
      requirements: {"globs": "requirements/*.txt"}
      py_and_requirements: {"globs": ["requirements/*.txt", "*.py"]}

      The separateDeleted boolean determines if we separate out deleted files or if they're included in the change list.
outputs:
  any-matches:
    description: 'A boolean value indicating if any glob matches were found'

runs:
  using: 'node20'
  main: 'dist/index.js'
